Repository metwork-framework/mfsysmon, pull requests merged in 2018-12, with the labels that each got.

#39 doc: add some docs
  config/config.ini
Labels: Status: Review Needed

#38 feat: add telegraf (internal) monitoring
  config/telegraf.conf.custom
Labels: Merge Now, Status: Pending

#40 feat: better diskio configuration
  adm/Makefile
  adm/_list_partitions.py
  config/config.ini
  config/telegraf.conf.custom
Labels: Merge Now, Status: Pending

#41 feat: add a custom implementation of diskio plugin
  adm/Makefile
  adm/telegraf_collector_custom_diskio.py
  config/circus.ini.custom
Labels: Merge Now, Status: Review Needed

#43 refactor: telegraf itself monitoring moving to core config
  config/telegraf.conf.custom
Labels: Status: Review Needed

#45 feat: add a custom netstat telegraf collector
  adm/Makefile
  adm/telegraf_collector_custom_netstat.py
  config/circus.ini.custom
Labels: Merge Now, Status: Review Needed

#46 feat: add a custom netio telegraf collector
  adm/Makefile
  adm/telegraf_collector_custom_netio.py
  config/circus.ini.custom
Labels: Status: Review Needed

#48 build: clean old diskio plugin
  config/config.ini
  config/telegraf.conf.custom
Labels: Merge Now, Status: Review Needed, backport-to-0.4

#47 feat: add an entry-point for external systems to inject metrics
  config/config.ini
  config/telegraf.conf.custom
Labels: Merge Now, Status: Review Needed
