Repository metwork-framework/mfsysmon, pull requests merged in 2019-05, with the labels that each got.

#57 docs: Update MFSYSMON documentation
  .gitignore
  bootstrap.sh
  doc/Makefile
  doc/_images/logo-metwork.png
  doc/_images/metwork.ico
  doc/_static/css/override_theme.css
  doc/_templates/breadcrumbs.html
  doc/_templates/layout.html
  doc/changelogs.rst
  doc/conf.py
  doc/index.rst
  doc/mfsysmon_intro.md
  doc/mfsysmon_miscellaneous.md
  doc/todo.rst
  layer_custom.md
  layers/layer9_default/layer_custom.md
Labels: Status: Review Needed

#58 build: fix gitignore
  .gitignore
Labels: Merge Now

#59 feat: use envtpl new option --reduce-multi-blank-lines
  doc/Makefile
Labels: Merge Now, Status: Review Needed
