Repository metwork-framework/mfsysmon, pull requests merged in 2019-06, with the labels that each got.

#60 docs: generate automatically changelogs entries in changelogs.rst file + Update MFSYSMON documentation
  .gitignore
  doc/Makefile
  doc/_images/overall_architecture.svg
  doc/changelogs.tmpl
  doc/mfsysmon_intro.md
  doc/src/overall_architecture.graphml
Labels: Status: Review Needed

#62 docs: Update MFSYSMON documentation
  doc/_images/overall_architecture.svg
  doc/mfsysmon_intro.md
  doc/src/overall_architecture.graphml
Labels: Status: Review Needed

#63 docs: fix typo
  doc/mfsysmon_intro.md
Labels: Status: Review Needed

#64 fix: send_mflog_logs config key was missing
  config/config.ini
Labels: Status: Review Needed, backport-to-0.7

#66 Experimental
  bootstrap.sh
Labels: Merge Now, Status: Review Needed
